---
title: "Assessing Video Game Mechanics"
author: "Danya Zhang"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(pander)
library(factoextra)
```

# Visualizations
```{r}
# read in the data
game_df <- read_excel("TopSelling_MSSP_July28_GameData.xlsx")
participant_df <- read_excel("TopSelling_MSSP_July28_ParticipantData.xlsx")
```

```{r}
# create a subset of the game_df with just Num variables
game_df_num_subset <- game_df %>%
  dplyr::select(StudyGame, GameName, NumFam, NumOT, NumIV, NumSN, NumSP, NumCG)

# pivot data to prep for visualizations 
game_df_num_subset_longer <- game_df_num_subset %>% 
  pivot_longer(cols = c(NumOT, NumIV, NumSN, NumSP, NumCG), 
               names_to = "NumType", 
               values_to = "Count"
  )
```

```{r}
# stacked bar chart for the 5 game mechanics
ggplot(data = game_df_num_subset_longer, 
       aes(x = StudyGame, y = Count, fill = NumType)) + 
  geom_bar(position="stack", stat="identity", width = 0.75) +
  coord_flip() +
  scale_fill_brewer(palette = "YlGnBu", guide=guide_legend(reverse=T)) +
  theme(text = element_text(size=5),
        legend.position = "bottom", legend.box = "horizontal",
        legend.text = element_text(size = 8)) +
  xlab("StudyGame") + 
  labs(title = "Count of Video Game Mechanics") 


# order by length of bars
ggplot(data = game_df_num_subset_longer, 
      aes(x = reorder(StudyGame, Count, sum), y = Count, fill = NumType)) +
  geom_bar(position="stack", stat="identity", width = 0.75) +
  coord_flip() +
  scale_fill_brewer(palette = "YlGnBu", guide=guide_legend(reverse=T)) +
  theme(text = element_text(size=5),
        legend.position = "bottom", legend.box = "horizontal",
        legend.text = element_text(size = 8)) +
  xlab("StudyGame") + 
  labs(title = "Count of Video Game Mechanics") 
```

```{r}
# run a principal components analysis (PCA) to see which games are similar
game_df_pca <- game_df %>%
  dplyr::select(StudyGame, starts_with("Pct"))

pca_results <- prcomp(game_df_pca[, -1], scale = FALSE) 
pander(summary(pca_results))
```

```{r}
# we'd like to visualize the PCA results
fviz_pca_biplot(pca_results, 
                repel = TRUE,
                col.var = "deepskyblue",
                title = "Figure 1: Biplot", geom="point")

fviz_eig(pca_results,
         title = "Figure 2: Scree Plot")

```


